# Generated by Django 4.1.9 on 2023-06-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('Number', models.BigAutoField(auto_created=True, db_column='Number', db_index=True, primary_key=True, serialize=False, verbose_name='Number')),
                ('Bonus', models.PositiveIntegerField(db_column='Bonus', default=0, null=True, verbose_name='Bonus')),
                ('Type', models.CharField(db_column='Type', default='Стандартная', max_length=20, null=True, verbose_name='Type')),
            ],
            options={
                'db_table': 'BonusCard',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('Email', models.CharField(db_column='Email', max_length=100, verbose_name='Email')),
                ('PhoneNumber', models.CharField(db_column='PhoneNumber', max_length=12, verbose_name='PhoneNumber')),
                ('FullName', models.CharField(db_column='FullName', max_length=100, verbose_name='FullName')),
                ('Login', models.CharField(db_column='Login', max_length=50, verbose_name='Login')),
                ('Password', models.CharField(db_column='Password', max_length=70, verbose_name='Password')),
                ('Address', models.CharField(db_column='Address', max_length=200, null=True, verbose_name='Address')),
                ('Balance', models.PositiveIntegerField(db_column='Balance', default=0, verbose_name='Balance')),
                ('BonusCardNumber', models.ForeignKey(db_column='BonusCardNumber', null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.bonuscard')),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', db_index=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('Title', models.CharField(db_column='Title', default='default title', max_length=30)),
                ('Subcategory', models.CharField(db_column='Subcategory', default='default Subcategory', max_length=30)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('FullName', models.CharField(db_column='FullName', max_length=100, verbose_name='FullName')),
                ('Salary', models.PositiveIntegerField(db_column='Salary', default=0, verbose_name='Salary')),
                ('PhoneNumber', models.CharField(db_column='PhoneNumber', max_length=12, verbose_name='PhoneNumber')),
            ],
            options={
                'db_table': 'Courier',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('Title', models.CharField(db_column='Title', max_length=100, verbose_name='Title')),
                ('Responsibilities', models.TextField(db_column='Responsibilities', verbose_name='Responsibilities')),
            ],
            options={
                'db_table': 'JobTitle',
            },
        ),
        migrations.CreateModel(
            name='OfflineStore',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('Address', models.CharField(db_column='Address', max_length=200, null=True, verbose_name='Address')),
                ('OpeningTime', models.TimeField(db_column='OpeningTime', verbose_name='OpeningTime')),
                ('ClosingTime', models.TimeField(db_column='ClosingTime', verbose_name='ClosingTime')),
            ],
            options={
                'db_table': 'OfflineStore',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('CompanyName', models.CharField(db_column='CompanyName', max_length=50, null=True, verbose_name='CompanyName')),
                ('Address', models.CharField(db_column='Address', max_length=200, null=True, verbose_name='Address')),
                ('Mail', models.CharField(db_column='Mail', max_length=100, verbose_name='Email')),
            ],
            options={
                'db_table': 'Producer',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('FullName', models.CharField(db_column='FullName', max_length=100, verbose_name='FullName')),
                ('Email', models.CharField(db_column='Email', max_length=100, verbose_name='Email')),
                ('PhoneNumber', models.CharField(db_column='PhoneNumber', max_length=12, verbose_name='PhoneNumber')),
                ('Salary', models.PositiveIntegerField(db_column='Salary', default=0, null=True, verbose_name='Cost')),
                ('Login', models.CharField(db_column='Login', max_length=50, verbose_name='Login')),
                ('Password', models.CharField(db_column='Password', max_length=70, verbose_name='Password')),
            ],
            options={
                'db_table': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('Title', models.CharField(db_column='Title', max_length=50, null=True, verbose_name='Title')),
                ('Cost', models.PositiveIntegerField(db_column='Cost', default=0, null=True, verbose_name='Cost')),
                ('Count', models.PositiveIntegerField(db_column='Count', default=0, null=True, verbose_name='Count')),
                ('Size', models.PositiveIntegerField(db_column='Size', default=0, null=True, verbose_name='Size')),
                ('Color', models.CharField(db_column='Color', max_length=50, null=True, verbose_name='Color')),
                ('ImageUrl', models.ImageField(db_column='ImageUrl', null=True, upload_to='img/%Y-%m-%d/', verbose_name='ImageUrl')),
                ('Category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Category')),
                ('Producer', models.ForeignKey(db_column='Producer', on_delete=django.db.models.deletion.PROTECT, to='shop.producer', verbose_name='Producer')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('FullName', models.CharField(db_column='FullName', max_length=100, verbose_name='FullName')),
                ('PhoneNumber', models.CharField(db_column='PhoneNumber', max_length=12, verbose_name='PhoneNumber')),
                ('Email', models.CharField(db_column='Email', max_length=100, verbose_name='Email')),
                ('Salary', models.PositiveIntegerField(db_column='Salary', default=0, verbose_name='Salary')),
                ('JobTitle', models.ForeignKey(db_column='JobTitle', on_delete=django.db.models.deletion.PROTECT, to='shop.jobtitle')),
                ('OfflineStore', models.ForeignKey(db_column='OfflineStore', on_delete=django.db.models.deletion.PROTECT, to='shop.offlinestore')),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('Count', models.PositiveIntegerField(db_column='Count', default=0, verbose_name='Count')),
                ('CostDelivery', models.PositiveIntegerField(db_column='CostDelivery', default=0, null=True, verbose_name='CostDelivery')),
                ('Type', models.CharField(db_column='Type', max_length=20, null=True, verbose_name='Type')),
                ('DeliveryDate', models.DateField(db_column='DeliveryDate', null=True, verbose_name='DeliveryDate')),
                ('Retrieved', models.BooleanField(db_column='Retrieved', null=True, verbose_name='Retrieved')),
                ('CostProduct', models.PositiveIntegerField(db_column='CostProduct', default=0, null=True, verbose_name='CostProduct')),
                ('Bonuses', models.PositiveIntegerField(db_column='Bonuses', default=0, null=True, verbose_name='Bonuses')),
                ('Address', models.CharField(db_column='Address', max_length=200, null=True, verbose_name='Address')),
                ('Buyer', models.ForeignKey(db_column='Buyer', on_delete=django.db.models.deletion.PROTECT, to='shop.buyer')),
                ('Courier', models.ForeignKey(db_column='Courier', null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.courier')),
                ('Product', models.ForeignKey(db_column='Product', on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OnlineStore',
            fields=[
                ('Address', models.UUIDField(db_column='Address', primary_key=True, serialize=False, verbose_name='Address')),
                ('Product', models.ForeignKey(db_column='Product', on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
                ('Support', models.ForeignKey(db_column='Support', on_delete=django.db.models.deletion.PROTECT, to='shop.support')),
            ],
            options={
                'db_table': 'OnlineStore',
            },
        ),
        migrations.CreateModel(
            name='OfflineStoreProducts',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('OfflineStore', models.ForeignKey(db_column='OfflineStore', on_delete=django.db.models.deletion.PROTECT, to='shop.offlinestore')),
                ('Product', models.ForeignKey(db_column='Product', on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'db_table': 'OfflineStoreProducts',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('Count', models.PositiveIntegerField(db_column='Count', default=0, null=True, verbose_name='Count')),
                ('Buyer', models.ForeignKey(db_column='Buyer', on_delete=django.db.models.deletion.PROTECT, to='shop.buyer')),
                ('Product', models.ForeignKey(db_column='Product', on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
