# Generated by Django 4.1.9 on 2023-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(db_column='Address', max_length=200, null=True, verbose_name='Address'),
        ),
    ]
